
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: glitzglam_development

test:
  <<: *default
  database: glitzglam_test

production:
  <<: *default
  database: glitzglam_production
  username: glitzglam
  password: <%= ENV['GLITZGLAM_DATABASE_PASSWORD'] %>
